global:
  scrape_interval: 5s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ["localhost:8080"]
 
  - job_name: apbank
    honor_labels: true
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]